### ISSUE TITLE
Version 1.0 not finding the controller

### ISSUE THREAD

**Issue by usingapc** [bdunn44/hass-jellyfish-lighting#1]
@bdunn44 THANKS FOR ALL YOUR EFFORTS AROUND THIS!!!

I was finally able to get your beta version installed on Christmas Eve.  While it didn't have the actual state of the zones, it worked great and I was able to create several scripts and automations using it and specific zones and effects.

I tried to upgrade to version 1.0 and I'm now getting the error: "Could not connect to controller at specified host/IP."  Originally the existing integration just showed an error.  even after reloading.  I then deleted it completely an tried a fresh install via HACS.  It installs fine but can't find my controller.  The controller is active and the same static IP.

Thanks!

**Comment by usingapc** [comment]
Also, @bdunn44 you need to get a buy my a coffee link on this repo ;)

**Comment by bdunn44** [comment]
You are very welcome! 

Not sure what this issue could be... I just released version 0.1.1 with some minor tweaks - can you give that a try? If it's still not working please send any error messages / stack traces you see in the logs, and of course double check the IP/host you are entering.

Also added a link to buy me a coffee - appreciate it!

**Comment by usingapc** [comment]
Good Morning @bdunn44 I tried again to upgrade to 0.1.1.  I'm getting the same error.  Here is what I can find in the logs: 

```
2022-12-28 08:43:33.142 INFO (MainThread) [homeassistant.setup] Setting up jellyfish_lighting
2022-12-28 08:43:33.142 INFO (MainThread) [homeassistant.setup] Setup of domain jellyfish_lighting took 0.0 seconds
2022-12-28 08:43:33.148 INFO (MainThread) [custom_components.jellyfish_lighting] Setting up Jellyfish Lighting integration
2022-12-28 08:43:33.149 INFO (MainThread) [custom_components.jellyfish_lighting] 
-------------------------------------------------------------------
Jellyfish Lighting
Version: 0.1.1
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/bdunn44/hass-jellyfish-lighting/issues
-------------------------------------------------------------------


2022-12-28 08:43:33.232 ERROR (MainThread) [custom_components.jellyfish_lighting] Failed to connect and get data from Jellyfish Lighting controller at 10.0.200.235
Traceback (most recent call last):
  File "/config/custom_components/jellyfish_lighting/api.py", line 42, in async_get_data
    self._controller.getRunPattern, zone
AttributeError: 'JellyFishController' object has no attribute 'getRunPattern'
2022-12-28 08:43:33.234 ERROR (MainThread) [custom_components.jellyfish_lighting] Error fetching jellyfish_lighting data: 
2022-12-28 08:43:33.237 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Jellyfish Controller' for jellyfish_lighting integration not ready yet: None; Retrying in background
```
I tried removing and re-adding again but still have the same issue.  I noticed in your updates something about removing the capability for multiple controllers.  I wonder if it is seeing this as a second controller somehow?

**Comment by bdunn44** [comment]
Ahh the problem here is it's using an old version of the `jellyfishlights-py` library that doesn't have the `getRunPattern` function (this is what retrieves the current state of the zones). It's a little bit hacked at the moment because that latest change hasn't been published to PyPI yet, so I'm pointing to the Git repository instead of an official package.

It should still work, though. Can you try to explicitly remove the integration from HACS (go to Jellyfish Lighting -> Upper right menu -> click "Remove"), then remove the custom repo entry, and finally re-add and install the component? My hope is this will force the re-installation of the dependency.

**Comment by usingapc** [comment]
Thanks for the quick reply.  I tried that but no luck.  I even tried, 1.1, 1.2, & the new 1.3 version.  All are failing the same way.

**Comment by bdunn44** [comment]
Sorry to hear that @usingapc... A couple of ideas:

1. Try the `1.0.0` version I just released. It removes the Git dependency in favor of the official package.
2. If that still doesn't work, first remove the custom repo completely as I described above, then shut down Home Assistant, SSH into your Home Assistant installation (server/image), and manually remove the library by running `pip3 uninstall jellyfishlights-py` (if that doesn't work try `python -m pip uninstall jellyfishlights-py`). It will be reinstalled when you re-add the custom component.

As a side note, I just submitted this repo to be included in the official HACS listing so you can search for it directly vs. adding it as a custom repository. Don't think that helps you here, though.

**Comment by usingapc** [comment]
version 1.0.0 fixed the issue.  Thanks for your efforts around this!
