### ISSUE TITLE
Jellyfish Cloud

### ISSUE THREAD

**Issue by johnnyo21** [bdunn44/hass-jellyfish-lighting#17]
Jellyfish just announced the addition of a cloud connected app. If we upgrade the firmware in our systems, will it cause problems for our local control via home assistant?

**Comment by bdunn44** [comment]
I missed this, sorry for the delayed response. I'm not aware of any updates that will cause local control to break. Do you have a link to the announcement that you can share?

**Comment by johnnyo21** [comment]
It was an email sent from them on June 6, however, after looking at the website [https://jellyfishlighting.com/app-updates/](url) it appears that the cloud app has been out for a little while.

**Comment by bdunn44** [comment]
You're right, it has. And their legacy JellyFish Designer app still relies on the local API, so if they decide to block local access I would expect an announcement related to retiring that app. Will close this for now
