### ISSUE TITLE
Legal Considerations

### ISSUE THREAD

**Issue by vinenoob** [bdunn44/hass-jellyfish-lighting#2]
To start off, I am not a lawyer and am not well versed in law. I do however work for JellyFish and personally think this is cool and I'd hate to see it get in trouble of some sort.

You may want to make it apparent that this is not an official JellyFish Lighting product. I wonder about the usage of the JellyFish logo too.

Just trying to get ahead of any potential problems

**Comment by bdunn44** [comment]
Good callout - thanks @vinenoob! Just added statements to the readmes that make it clear this is an unofficial integration as well as a trademark statement regarding the logo.
