### ISSUE TITLE
"title" directly to update a config entry

### ISSUE THREAD

**Issue by markus99** [bdunn44/hass-jellyfish-lighting#21]
Recently upgraded to 2024.4.x

Detected that custom integration 'jellyfish_lighting' sets "title" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/jellyfish_lighting/__init__.py, line 52: entry.title = f"{client.name} ({client.hostname})", please create a bug report at https://github.com/bdunn44/hass-jellyfish-lighting/issues

**Comment by bdunn44** [comment]
Thank you for reporting! Will get this updated

**Comment by markus99** [comment]
Currently running v1.2 and still showing this error.  Commenting as we're getting closer to 2024.9 deadline.  Thank you!

**Comment by bdunn44** [comment]
Same as #22 :) Please try upgrading to 1.3
