### ISSUE TITLE
'jellyfish_lighting' calls `async_add_job`, which is deprecated

### ISSUE THREAD

**Issue by markus99** [bdunn44/hass-jellyfish-lighting#22]
Recently upgraded to 2024.4.x

Detected that custom integration 'jellyfish_lighting' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/jellyfish_lighting/__init__.py, line 68: hass.async_add_job(hass.config_entries.async_forward_entry_setup(entry, LIGHT)), please create a bug report at https://github.com/bdunn44/hass-jellyfish-lighting/issues

**Comment by bdunn44** [comment]
Thank you for reporting! Will get this updated

**Comment by markus99** [comment]
Currently running v1.2 and still showing this error.  Commenting as we're getting closer to 2024.9 deadline.  Thank you!

**Comment by bdunn44** [comment]
Hi @markus99  thanks for the nudge. V1.3 fixes this but I had it marked as a pre-release. Just made it official -please upgrade and let me know if you still see it

**Comment by markus99** [comment]
This one appears to be cleared up with 1.3, thank you!

As your newly created https://github.com/bdunn44/hass-jellyfish-lighting/issues/25 shows, sadly seems a few more crept in.  D@mn you HA for continually changing things ;)
