### ISSUE TITLE
Automations 

### ISSUE THREAD

**Issue by xnigelx** [bdunn44/hass-jellyfish-lighting#27]
**Is your feature request related to a problem? Please describe.**
Bryson, thanks for this integration. I am trying to remove the schedule from my jellyfish app and utilize HA. I am unable to see any way to set up an automation, it seems to only have on/off, toggle, and brightness. Is there anyway to get an automation going?

**Describe the solution you'd like**
Would love to see lights on off, and whatever built in options for scenes. ie Spooky Halloween, Halloween Chase etc

**Describe alternatives you've considered**
n/a

**Additional context**
Thanks again for your work on this!

**Comment by bdunn44** [comment]
Hey! There shouldn't be any problem doing automations - I do all my scheduling through HA myself. Not sure why you're only seeing on/off and brightness but the light entities do have the ability to set a solid color and apply a preset pattern as well (by setting the "effect" attribute). If you can send more details about the steps you're taking and ideally screenshots I can help you troubleshoot. Here's some screenshots from the phone app.

![image](https://github.com/user-attachments/assets/084428a9-dc59-4e48-9256-1eeaf0f370a1)

![image](https://github.com/user-attachments/assets/405af9f6-dae9-4b69-aef3-fed0d1d67ff5)

**Comment by xnigelx** [comment]
When i click create a new automation I select device. Then i select Home
which is my jellyfish and the options below are all I see. The only place i
can select the effect is in the device itself. Is it possible that the
effect shouldnt be in the automation? Should I be selecting the effect from
the devices, and then the automation simply turns it on? If so then that's
my mistake
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by xnigelx** [comment]
![Screenshot 2024-09-25 191236](https://github.com/user-attachments/assets/80976172-2314-444a-9913-412445474acd)
![image (1)](https://github.com/user-attachments/assets/24259b8c-ef46-414d-a8a1-762597fe7053)
![image](https://github.com/user-attachments/assets/7b24d8a4-f9fe-4d01-8697-4eda2e3af753)

**Comment by usingapc** [comment]
When you create an automation you should use the Light Turn On action.
Inside of that action you need to select your Jellyfish light entity.
Inside of the Light Turn On action you can select your Effect to run when
it turns on.

**Comment by bdunn44** [comment]
Yeah exactly, instead of trying to create an automaton on the device,    try creating one from scratch that calls the light.turn_on service. Then select the entities (zones) you want to control and set the color/effect.

I've noticed in my version the effect attribute doesn't have a drop down in the mobile app... seems like a bug. But if you have trouble with this you could always create a scene with the light(s) set to how you want them, then use an automation to activate the scene.

Hope this all makes sense

**Comment by xnigelx** [comment]
I swear I'm not completely dumb. Still a bit new to HA. I created an automation from scratch selected turn on lights, chose my two entities if i hit the checkbox for "effect" there is no dropdown or selection, it basically wants me to enter text. Just for shits n giggles i tried the mobile app and same results.

![crap](https://github.com/user-attachments/assets/89627457-1c92-4ded-846d-95fd4259f039)

**Comment by bdunn44** [comment]
Ha! Yeah that's what I mentioned in my previous comment. That seems like an HA bug. A simple workaround would be to create a scene that turns on your lights and sets the effects you want, then activate the scene with the automation. 

The extra step is annoying but will definitely work. Alternatively you could try manually typing in the effect you want - for example, "Halloween/Spookiest"

**Comment by xnigelx** [comment]
> Ha! Yeah that's what I mentioned in my previous comment. That seems like an HA bug. A simple workaround would be to create a scene that turns on your lights and sets the effects you want, then activate the scene with the automation.
> 
> The extra step is annoying but will definitely work. Alternatively you could try manually typing in the effect you want - for example, "Halloween/Spookiest"

I will give it ago. Thanks for the quick support Sir, i greatly appreciate it!

**Comment by bdunn44** [comment]
Good luck! Feel free to reply here if you need help
